### ISSUE TITLE
Resize BBG image to 4GB

### ISSUE THREAD

**Issue by dmiklic** [assisi/casu-beaglebone#44]
Use all the flash memory availble.

**Comment by marselap** [comment]
Can be done on line by deleting partition and creating a bigger one in the partition table (using fdisk).

**Comment by dmiklic** [comment]
Please add the exact commands for future reference.

**Comment by marselap** [comment]
`sudo fdisk /dev/mmcblk1`
`Command (m for help): d
Selected partition 1
Partition 1 has been deleted.

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 1
First sector (2048-7553023, default 2048): 8192
Last sector, +sectors or +size{K,M,G,T,P} (8192-7553023, default 7553023): 

Created a new partition 1 of type 'Linux' and of size 3.6 GiB.

Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Device or resource busy

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
`
`sudo resize2fs /dev/mmcblk1p1`
I will also add them to setup instructions.

**Comment by marselap** [comment]
50e11bc
